[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "psutil>=7.0.0",
    "pytest>=8.4.2",
    "pytest-cov>=6.3.0",
    "pytest-timeout>=2.4.0",
    "ruff>=0.12.12",
]

[project.scripts]
testgen = "testgen.cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["testgen*"]
